# Generated by Django 2.2.16 on 2020-11-02 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Bar',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(unique=True)),
                ('lon', models.FloatField(unique=True)),
                ('description', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('bar', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='bars.Bar')),
            ],
            options={
                'verbose_name_plural': 'Address',
            },
        ),
    ]
